# Generated by Django 2.2 on 2020-05-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='')),
                ('text1', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['create_at'],
            },
        ),
    ]
