# Generated by Django 2.2 on 2020-05-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200525_2045'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='post_table',
        ),
    ]
