# Generated by Django 2.2 on 2020-05-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200525_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text1',
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
