# Generated by Django 2.2 on 2020-06-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_contentimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentImage',
        ),
    ]
