# Generated by Django 2.2 on 2020-06-07 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_delete_contentimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='timestamp',
        ),
    ]
